### DB1.py

In [19]:
import sqlite3

#연결 객체를 리턴
# con = sqlite3.connect(":memory:")
con = sqlite3.connect(r"c:\wd\sample.txt")
#커서객체 리턴
cur = con.cursor()
#테이블 생성 (creat)
cur.execute("create table Phonebook (name text, phone text);")
#삽입(insert)
cur.execute("insert into Phonebook values ('Alice', '123-4567');")   

name = 'Bob'
phone = '987-6543'

cur.execute("insert into Phonebook values (?, ?)", (name, phone))   



# 여러건 입력
# datalist = " Chris, 555-1234; David, 444-5678; Eve, 333-8765"    
datalist = (("Chris", "555-1234"), ("David", "444-5678"), ("Eve", "333-8765"))
# for data in datalist.split(';'):
#     name, phone = data.split(',')
#     cur.execute("insert into Phonebook values (?, ?)", (name.strip(), phone.strip()))           
cur.executemany("insert into Phonebook values (?, ?);", datalist)

#조회
cur.execute("select * from Phonebook")
for row in cur:
    print(row)  

#작업을 정상적 종료

con.commit()

('Alice', '123-4567')
('Bob', '987-6543')
('Chris', '555-1234')
('David', '444-5678')
('Eve', '333-8765')

In [ ]:
# 전자제품 데이터 입출력용 SQLite 클래스 예제
import sqlite3
import random

class ElectronicsDB:
    def __init__(self, db_path=':memory:'):
        self.conn = sqlite3.connect(db_path)
        self.cur = self.conn.cursor()
        self.create_table()

    def create_table(self):
        self.cur.execute("""
            CREATE TABLE IF NOT EXISTS Electronics (
                id INTEGER PRIMARY KEY,
                name TEXT,
                price INTEGER
            )
        """)
        self.conn.commit()

    def insert(self, id, name, price):
        self.cur.execute(
            "INSERT INTO Electronics (id, name, price) VALUES (?, ?, ?)",
            (id, name, price)
        )
        self.conn.commit()

    def update(self, id, name=None, price=None):
        if name is not None and price is not None:
            self.cur.execute(
                "UPDATE Electronics SET name=?, price=? WHERE id=?",
                (name, price, id)
            )
        elif name is not None:
            self.cur.execute(
                "UPDATE Electronics SET name=? WHERE id=?",
                (name, id)
            )
        elif price is not None:
            self.cur.execute(
                "UPDATE Electronics SET price=? WHERE id=?",
                (price, id)
            )
        self.conn.commit()

    def delete(self, id):
        self.cur.execute("DELETE FROM Electronics WHERE id=?", (id,))
        self.conn.commit()

    def select(self, id=None):
        if id is None:
            self.cur.execute("SELECT * FROM Electronics")
            return self.cur.fetchall()
        else:
            self.cur.execute("SELECT * FROM Electronics WHERE id=?", (id,))
            return self.cur.fetchone()

# 샘플 데이터 100개 생성 및 삽입
db = ElectronicsDB('electronics_sample.db')
product_names = [f"제품{i}" for i in range(1, 101)]
for i, name in enumerate(product_names, 1):
    price = random.randint(10000, 1000000)
    db.insert(i, name, price)

# CRUD 예시
print('전체 데이터 개수:', len(db.select()))
print('1번 제품:', db.select(1))
db.update(1, name='수정된제품', price=55555)
print('수정 후 1번 제품:', db.select(1))
db.delete(1)
print('삭제 후 1번 제품:', db.select(1))

변경했습니다.

파이썬에서 SQLite를 사용해 전자제품 데이터(제품ID, 제품명, 가격)를 입출력하는 클래스를 추가했습니다.  
- insert, update, delete, select 메서드를 포함하고,  
- 샘플 데이터 100개를 자동 생성해 DB에 저장합니다.  
- 각 CRUD 동작 예시도 포함되어 있습니다.

해당 코드는 마지막(3번째) 코드 셀에 추가되었습니다.  
원하시는 추가 기능이나 설명이 있으면 말씀해 주세요!